# Custom Language File for Launcher Customizer

[ejs.app]
title = "힐링월드 시즌2"

[ejs.landing]
mediaGitHubURL = "#"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/4jGT3kDc4f"

[ejs.settings]
sourceGithubLink = "https://github.com/rhythembear/healing-launcher"
supportLink = "https://github.com/rhythembear/healing-launcher/issues"

[ejs.welcome]
welcomeHeader = "힐링월드 시즌2에 오신 것을 환영합니다."
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
